#!/bin/bash

set -e

# Load environment variables from the .env file
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

if [ -z $REMOTE ]; then
  echo 'Error: REMOTE is not set in the .env file, or the .env file is missing.'
  exit 1
fi

local_path=./
final_path=/var/www/personal-website

echo "Deploying to $REMOTE:$final_path..."

rsync -rv --delete --rsync-path="sudo rsync" \
  $local_path/*.html $local_path/*.css $REMOTE:$final_path